# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default]
[default.global.parameters]
stack_name = "sp-api-stack"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_NAMED_IAM"
confirm_changeset = true
resolve_s3 = true
s3_prefix = "sp-api-stack"
region = "us-east-2"
disable_rollback = false
image_repositories = []
tags = "sp=\"1\" sp-api=\"1\""

[default.local_start_lambda.parameters]
warm_containers = "EAGER"
