services:
  dynamodb-local:
    # Below command is from https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBLocal.DownloadingAndRunning.html. Do not use it. Causes error.
    # command: -jar DynamoDBLocal.jar -sharedDb -dbPath ./data 
    image: amazon/dynamodb-local:latest
    container_name: dynamodb-local
    ports:
      - 8000:8000
    volumes:
      - ./dynamodb:/home/dynamodblocal/data
    working_dir: /home/dynamodblocal
